import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Nav from '@/components/Nav'
import Top from '@/components/Top'
import AllPokemon from '@/components/AllPokemon'
import Details from '@/components/Details'
export default function Home() {
  return (
    <>
      <Head>
        <title>Pokédex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Nav />
        <Top />
        <AllPokemon />
        <Details />
      </main>
    </>
  )
}
